name: 'BMW 525D Touring '
favicon: null
layout_spectrum: 0.52719
typography_spectrum: 0.47011102084070444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050505'
    - '#98b1d1'
    - '#2e2e2e'
    - '#76859a'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
